title: "[IF Idea] "
labels: ["if-team-idea"]
body:
  - type: markdown
    attributes:
      value: "Please use this template to suggest an idea that people can try to implement as part of Carbon Hack 24. Provide as much detail as possible. If someone else submitted an idea but you feel you can do a better job of explaining, please go ahead and submit again."
  - type: checkboxes
    id: prize-category
    attributes:
      label: "Prize category"
      description: "Help the participant understand which of the prize categories this idea would best fit"
      options:
        - label: Best Model
        - label: Best Content
        - label: Beyond Carbon
        - label: Best contribution to the framework        
    validations:
      required: true      
  - type: textarea
    id: user-story
    attributes:
      label: "User Story"
      description: "Describe the benefits of this change, ideally in the following format"
      placeholder: "As a < type of user >, I want < some goal > so that < some reason >"
    validations:
      required: true      
  - type: textarea
    id: rationale
    attributes:
      label: "Rationale"
      description: "Provide the relevant background information to understand why this is a useful thing to work on"
      placeholder: "This is where you can provide more details that help the reader understand why you want to make this change"
    validations:
      required: true        
  - type: textarea
    id: impact
    attributes:
      label: "Impact"
      description: "Finish this sentence:"
      placeholder: "If this idea is successful implemented the ...."
    validations:
      required: true              
  - type: textarea
    id: implementation-guidelines
    attributes:
      label: "Implementation guidelines"
      description: "If there are specific implementation details that are REQUIRED or PREFERRED please describe them here e.g. this model MUST conform to the ModelPlugin interface e.g. this feature MUST be part of the supercomputer module e.g. this feature SHOULD be be a model plugin"
    validations:
      required: true                    
  - type: textarea
    id: difficulty
    attributes:
      label: "Difficulty"
      description: "Provide an assessment of the expected difficulty from 1-5 to help hackers find tasks at their preferred skill level"
    validations:
      required: true                          
  - type: textarea
    id: scope
    attributes:
      label: "Scope of Work"
      description: "List some of the tasks that will be required to implement this idea"
    validations:
      required: true                          
  - type: textarea
    id: examples
    attributes:
      label: "Examples & Resources"
      description: "Provide any links to prior discussions, similar code, examples, pseudocode, diagrams or anything else than can help the hacker understand the task"
    validations:
      required: true                          
  - type: textarea
    id: manifest
    attributes:
      label: "Manifest file"
      description: "Provide a dummy Mmnifest file to help the implementer understand how this functionality will be executed, provide them with the necessary data, observations and structure so they can move fast with development."
      render: bash      
    validations:
      required: true                          
