title: ""
labels: ["if-team-idea"]
body:
  - type: markdown
    attributes:
      value: |
        Please use this template to suggest an idea that people can try to implement as part of Carbon Hack 24. Provide as much detail as possible. If someone else submitted an idea but you feel you can do a better job of explaining, please go ahead and submit again.
