name: Hackathon Project
description: "Raise your Carbon Hack 24 project"
title: "[Your project name]"
labels: ["draft"]
projects: ["Green-Software-Foundation/projects/47"]
body:
  - type: markdown
    attributes:
      value: |
        Please complete the form below to raise your hackathon project
  - type: dropdown
    id: prize
    attributes:
      label: Prize category
      description: Select the [prize category](https://github.com/Green-Software-Foundation/hack/wiki/Prizes) you are entering for
      options:
        - Beyond Carbon
        - Best Content
        - Best Contribution to the Framework
        - Best Plugin
    validations:
      required: true      
  - type: textarea
    id: project-description
    attributes:
      label: Overview
      description: Tell us what you plan to build
    validations:
      required: true
  - type: textarea
    id: questions
    attributes:
      label: Questions to be answered
      description: Do you have any questions that you'd like us to clarify before you build your solution?
      placeholder: Your questions here
    validations:
      required: false
  - type: dropdown
    id: team
    attributes:
      label: Have you got a project team yet?
      description: Please answer so we know if you need help
      options:
        - Yes and we aren't recruiting
        - Yes and we are still open to extras members
        - No, but we will find people ourself
        - No, we would like your help to find team-mates
        - I am working on this project alone
    validations:
      required: true
  - type: textarea
    id: teamlist
    attributes:
      label: Project team
      description: Please list the GitHub usernames of every team mate in this hackathon project. Only people who's handles are listed in this text area will be recognised as team mates from the hackathon team.
      placeholder: e.g. @jawache
    validations:
      required: false      
  - type: checkboxes
    id: terms
    attributes:
      label: Terms of Participation
      description: 
      options:
        - label: I agree to the hackathon [Rules & Terms](https://github.com/Green-Software-Foundation/hack/wiki/Rules-and-Terms) and [Code of Conduct](https://github.com/Green-Software-Foundation/hack/wiki/Code-of-Conduct)
          required: true
