name: Hackathon Project
description: "Register your Carbon Hack 24 project"
title: "[Your project name]"
labels: ["draft"]
projects: ["Green-Software-Foundation/projects/47"]
assignees:
  - russelltrow
body:
  - type: markdown
    attributes:
      value: |
        Thank you for registering your project!
  - type: dropdown
    id: type
    attributes:
      label: Type of project
      options:
        - Building a plug-in for Impact Framework
        - Enhancing the Impact Framework
        - Writing content about Impact Framework
    validations:
      required: true
  - type: textarea
    id: project-description
    attributes:
      label: Overview
      description: Please give us an overview of your project
      placeholder: Tell us what you want to build!
    validations:
      required: true
  - type: textarea
    id: questions
    attributes:
      label: Questions to be answered
      description: Do you have any questions that you'd like us to clarify before you build your solution?
      placeholder: Your questions here
    validations:
      required: false
  - type: dropdown
    id: team
    attributes:
      label: Have you got a project team yet?
      description: Please answer so we know if you need help
      options:
        - Yes and we aren't recruiting
        - Yes and we are still open to extras members
        - No, but we will find people ourself
        - No, we would like your help to find team-mates
        - I am working on this project alone
    validations:
      required: true
  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: By submitting this issue, you agree to follow our [Code of Conduct](https://greensoftware.foundation/code-of-conduct)
      options:
        - label: I agree to follow this project's Code of Conduct
          required: true
