name: Hackathon Project
description: Submit your Carbon Hack 24 project
title: "[Project]: "
labels: ["draft project"]
projects: ["Green-Software-Foundation/projects/47"]
assignees:
  - russelltrow
body:
  - type: markdown
    attributes:
      value: |
        Thank you for submitting your project idea!
  - type: input
    id: team-name
    attributes:
      label: Team Name
      description: Do you have a team name already? Put it here if so. 
      placeholder: e.g. Team Awesome
    validations:
      required: false
  - type: textarea
    id: project-description
    attributes:
      label: Project overview
      description: Please give us an overview of your project
      placeholder: Tell us what you want to build!
    validations:
      required: true
  - type: dropdown
    id: prize
    attributes:
      label: Prize Category
      description: Please select the [prize category](https://github.com/Green-Software-Foundation/hack/blob/main/prizes.md) you are entering for
      options:
        - Beyond Carbon
        - Best Model
        - Best Content        
        - Best Contribution to the Framework
    validations:
      required: true
  - type: checkboxes
    id: student
    attributes:
      label: Undergraduate Student Prize
      description: All members of my team are undergraduate students and I want to be entered into this prize category in addition to the chosen prize category above.
      options:
        - label: All team members are students
          required: false
  - type: textarea
    id: questions
    attributes:
      label: Questions to be answered
      description: Do you have any questions that you'd like us to clarify before you build your solution?
      placeholder: Your questions here
    validations:
      required: false
  - type: dropdown
    id: team
    attributes:
      label: Have you got a project team yet?
      description: Please answer so we know if you need help
      options:
        - Yes and we aren't recruiting
        - Yes and we are still open to extras members
        - No, but we will find people ourself
        - No, we would like your help to find team-mates
        - I am working on this project alone
    validations:
      required: true
  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: By submitting this issue, you agree to follow our [Code of Conduct](https://greensoftware.foundation/code-of-conduct)
      options:
        - label: I agree to follow this project's Code of Conduct
          required: true
