name: Project Idea
description: Submit your project idea
title: "[Project Idea]: "
labels: ["project-idea"]
projects: ["Green-Software-Foundation/projects/47"]
assignees:
  - adamj89
body:
  - type: markdown
    attributes:
      value: |
        Thank you for submitting your project idea!
  - type: input
    id: team-name
    attributes:
      label: Team Name
      description: Do you have a team name already? Put it here if so. 
      placeholder: e.g. Team Awesome
    validations:
      required: false
  - type: textarea
    id: project-description
    attributes:
      label: Project overview
      description: Please give us an overview of your project
      placeholder: Tell us what you want to build!
    validations:
      required: true
  - type: dropdown
    id: prize
    attributes:
      label: Prize Category
      description: Please select the prize you are entering for
      options:
        - 1.0.2 (Default)
        - 1.0.3 (Edge)
      default: 0
    validations:
      required: true
  - type: checkboxes
    id: student
    attributes:
      label: Undergraduate Student Prize
      description: All members of my team are undergraduate students and I want to be entered into this prize category in addition to the chosen prize category above.
      options:
        - label: All team members are students
          required: false
  - type: dropdown
    id: browsers
    attributes:
      label: What browsers are you seeing the problem on?
      multiple: true
      options:
        - Firefox
        - Chrome
        - Safari
        - Microsoft Edge
  - type: textarea
    id: logs
    attributes:
      label: Relevant log output
      description: Please copy and paste any relevant log output. This will be automatically formatted into code, so no need for backticks.
      render: shell
  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: By submitting this issue, you agree to follow our [Code of Conduct](https://example.com)
      options:
        - label: I agree to follow this project's Code of Conduct
          required: true
